language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

addons:
  chrome: stable

env:
  - GO111MODULE=on

before_install:
  - go get -v golang.org/x/lint/golint

install:
- go get github.com/agnivade/wasmbrowsertest
- mv $GOPATH/bin/wasmbrowsertest $GOPATH/bin/go_js_wasm_exec
- export PATH=$GOPATH/bin:$PATH

script:
  - GOOS=js GOARCH=wasm go test -v ./...
